modLoader="javafml"
loaderVersion="47"
license="WTFPL"

[[mods]]
modId = "chestbubbles"
version = "1.0.1"
displayName = "Chest Bubbles Revived"
description = '''
Creates bubbles when chests are opened underwater.
'''

[[dependencies.chestbubbles]]
    modId="forge"
    mandatory=true
    versionRange="[43.3.22,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chestbubbles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.20.2)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.chestbubbles]]
    modId="ironchests"
    mandatory=false
    ordering="AFTER"
    side="BOTH"